# Generated by Django 5.2.6 on 2025-11-20 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['?']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['?']},
        ),
    ]

