# Generated by Django 5.2.6 on 2025-11-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptquestion',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
