# Generated by Django 5.2.6 on 2025-11-20 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_alter_option_options_alter_question_options'),
        ('exam', '0002_attemptquestion_score'),
    ]

    operations = [
    ]


