# Generated by Django 5.2.6 on 2025-11-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduletracking',
            name='final_exam_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moduletracking',
            name='final_exam_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moduletracking',
            name='final_exam_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moduletracking',
            name='final_exam_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moduletracking',
            name='is_final_exam',
            field=models.BooleanField(default=False),
        ),
    ]

