# Generated by Django 5.2.6 on 2025-11-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]


