# Generated by Django 5.2.6 on 2025-11-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name': 'Industry', 'verbose_name_plural': 'Industries'},
        ),
        migrations.AlterModelOptions(
            name='offeredby',
            options={'verbose_name': 'Offered By', 'verbose_name_plural': 'Offered Bys'},
        ),
    ]


