# Generated by Django 5.2.6 on 2025-11-26 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_industry_options_alter_offeredby_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='final_exam_completed',
        ),
        migrations.RemoveField(
            model_name='module',
            name='final_exam_completed_at',
        ),
        migrations.RemoveField(
            model_name='module',
            name='final_exam_started',
        ),
        migrations.RemoveField(
            model_name='module',
            name='final_exam_started_at',
        ),
    ]
