# Generated by Django 5.2.6 on 2025-11-26 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_code'),
        ('credential', '0002_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='badge', to='course.course'),
        ),
    ]


