# Generated by Django 5.2.6 on 2025-11-25 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userinfo_password_reset_token_and_more'),
        ('course', '0003_alter_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedemail',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allowed_emails', to='course.course'),
        ),
    ]


