# Generated by Django 5.2.6 on 2025-11-25 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_allowedemail_course'),
        ('course', '0003_alter_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedemail',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='allowed_emails', to='course.course'),
            preserve_default=False,
        ),
    ]

