# Generated by Django 5.2.6 on 2026-04-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_bulkallowedemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
